### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by ai** [corysimmons/postcss-ant#3]
https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md#21-plugin-must-be-tested

**Comment by ai** [comment]
I like [AVA](https://github.com/avajs/ava) for tests.

https://github.com/postcss/postcss-plugin-boilerplate/blob/master/test.js

**Comment by corysimmons** [comment]
Added some. I need to write some more for every possible case, but I'll do that over time.

Reckon this can be closed since there are a few in there.
