### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by smuemd** [corysimmons/postcss-ant#8]
Whats going on here?

**Comment by corysimmons** [comment]
I think I'm leaving open-source/GitHub.

I'll leave stuff on npm (it's actually useful) and have removed myself from Jeet/Lost.

Feel free to fork https://github.com/corysimmons/postcss-ant/commit/9f39eddb8df3671ec1cfede99351d8a7c5e54b6c if you need docs.

**Comment by smuemd** [comment]
Sorry to hear that.
Ant is your best work yet. You should keep it up even if only for sentimental reasons. There are people out there who really appreciate your stuff. Just hang on there...
