### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/postcss-ant#9]
@smuemd
@peterramsing 
@dbox
@jescalan
@kezzbracey

Feel free to rip out the Flow stuff and I'm happy to explain code if it isn't clear.

Leaving GitHub.

**Comment by IamManchanda** [comment]
So much anger on a simple tag!
I am sorry if i hurted you in a process .... Please dont leave github cory sir.... Github/OpenSource needs brains like you!

**Comment by corysimmons** [comment]
@IamManchanda I promise you this has nothing to do with you. In fact, I really appreciate you recognizing my ideas on grids and tagging me for my expertise.

This has been a long time coming. GitHub is a scam and I hope more people see it for what it really is.

**Comment by peterramsing** [comment]
Could we bring this API alongside LostGrid? I'm not looking for another project but could see bringing the two projects together? I'd be more than happy to co-maintain this, though!

Sorry to see you go, Cory. You've been an inspiration to me and many others. You'll be missed!

**Comment by peterramsing** [comment]
Just let me know how I can help out.

**Comment by corysimmons** [comment]
Yeah sure. I just migrated this to https://github.com/sylvainpolletvillard

The npm will always be up. You know my email so just email me if you need help with any of it.

**Comment by IamManchanda** [comment]
02 years CSS: Flexbox is default and natural
15 years CSS. Flexbox hurts my brain.
